### ISSUE TITLE
Continuing todo tasks list

### ISSUE THREAD

**Issue by AtiyahElsheikh** [MRC-CSO-SPHSU/LPMCalibration.jl#4]
Here are (some) in-going or planned activities. The order does not reflect any priorities or what will be done first (hints welcome) 

- [ ] Fitness Indices 
     - [ ] PP ( Population Pyramid Index) 
     - [ ] M (# of Marriages) 
     - [ ] D (# of Divorces) 
     - [ ] HWD (Husband-Wife Age Difference Distribution) 
     - [ ] MA (# Of Marriages by Age) 
     - [ ] DA (# Of Age by Divorces) 
     - [ ] HS (Household size distribution) 
     - [ ] LPH (Share of lone parents)
     - [ ] MPH (Share of  married couples by number of children) 
     - [ ] LPC (Share of lone parents by number of children) 
     - [ ] SCA (Number of people for SES category by age)
- [ ] Model tuning 
     - [ ] Considering slightly extra male population 
     - [ ] Immigration (In / Out) data 
     - [ ] Significant events (WWs)
     - [ ] ...
- [ ] Configuration flags 
     - [ ] Active parameters and their bounds 
     - [ ] Meta parameters ( simulation & calibration) 
- [ ] Plots 
     - [ ] Population Pyramid histograms 
     - [ ] PP Error histograms  
     - [ ] ...
- [ ] Parallelisation 
- [ ] Algorithms 
     - [ ] Hybercube 
     - [ ] Differential Evolution 
     - [ ] ...
     - [ ] constraints among related parameters 
     - [ ] ...
